/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-04-14 07:21:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/include/menu.jsp", Long.valueOf(1586736670112L));
    _jspx_dependants.put("/include/dbinfo.jsp", Long.valueOf(1586848120371L));
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1586499054118L));
    _jspx_dependants.put("/include/tail.jsp", Long.valueOf(1586499143803L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

//MySQL ������ ���� ���� ����
String     dbstring = "jdbc:mysql://127.0.0.1/ezen?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC";
String     user      = "root";
String     pass      = "mySQL1234";

      out.write('\r');
      out.write('\n');
      ezen.Board myBoard = null;
      myBoard = (ezen.Board) _jspx_page_context.getAttribute("myBoard", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (myBoard == null){
        myBoard = new ezen.Board();
        _jspx_page_context.setAttribute("myBoard", myBoard, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>초간단 게시판</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#cccccc\" width=\"100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"center\" height=\"40px\"><strong>초간단 게시판</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\t\t\t<td width=\"150px\" height=\"400px\" align=\"center\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<a href=\"list.jsp?type=s\">학생용 게시판</a>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<a href=\"list.jsp?type=t\">교사용 게시판</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\">");
      out.write('\r');
      out.write('\n');

//검색 파라메터를 분석한다.
String category = request.getParameter("category");
String key       = request.getParameter("key");
String pageno  = request.getParameter("pageno");
String no         = request.getParameter("no");

//게시물 정보를 가져온다.

myBoard.DBOpen();

String mSelectSQL = "";

mSelectSQL += "select no,title,contents,type,hit ";
mSelectSQL += "from board ";
mSelectSQL += "where no = '" + no + "' ";
//out.print(mSelectSQL);

myBoard.OpenQuery(mSelectSQL);
myBoard.ResultNext();
String board_no    =  myBoard.getString("no");
String board_title  =  myBoard.getString("title");
String board_body =  myBoard.getString("contents");
String board_type  =  myBoard.getString("type");
String board_hit    =  myBoard.getString("hit");
myBoard.CloseQuery();

//MySQL 접속을 종료한다.
myBoard.DBClose();

      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction GoList()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(confirm(\"글쓰기를 취소하고 글보기로 이동하시겠습니까?\") != 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.location = \"view.jsp?category=");
      out.print( category );
      out.write("&key=");
      out.print( key );
      out.write("&pageno=");
      out.print( pageno );
      out.write("&no=");
      out.print( no );
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<form id=\"modify_form\" name=\"modify_form\" method=\"post\" action=\"modify_ok.jsp\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"category\" name=\"category\" value=\"");
      out.print( category );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"key\" name=\"key\" value=\"");
      out.print( key );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"pageno\" name=\"pageno\" value=\"");
      out.print( pageno );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"no\" name=\"no\" value=\"");
      out.print( no );
      out.write("\">\r\n");
      out.write("\t<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#fffff0\" width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"120px\" align=\"center\">분류</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select id=\"type\" name=\"type\">\r\n");
      out.write("\t\t\t\t\t");

					if(board_type.equals("0"))
					{
						
      out.write("<option value=\"0\" selected>공지</option>");

					}else
					{
						
      out.write("<option value=\"0\">공지</option>");

					}
					
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

					if(board_type.equals("1"))
					{
						
      out.write("<option value=\"1\" selected>자료</option>");

					}else
					{
						
      out.write("<option value=\"1\">자료</option>");

					}
					
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">제목</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" id=\"title\" name=\"title\" style=\"width:100%\" value=\"");
      out.print( board_title );
      out.write("\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">내용</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<textarea  style=\"width:100%\" rows=\"10\" id=\"contents\" name=\"contents\">");
      out.print( board_body );
      out.write("</textarea>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" height=\"40\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"저장하기\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"작성취소\" onclick=\"javascript:GoList();\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" height=\"30px\" align=\"center\">Copyright ezen. 2020.</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
